### ISSUE TITLE
我没有CSDN的下载积分怎么下载即用版本？

### ISSUE THREAD

**Issue by wz36125** [NRatel/TextureUnpacker#1]
如题

**Comment by NRatel** [comment]
改成了0积分，正在审核，显示最多两天，也可能很快。
或者你用 Unity 打开这个项目，打个 Win64 的包就行。

**Comment by wz36125** [comment]
> 改个0积分，正在审核中，最多显示 这个项目，也有可能。或者你用Unity打开，轻松打出Win64的包就行了。

感谢回复，但是我依然不能下载，CSDN需要充值会员或者下载码，这两样我都没有。。。

**Comment by NRatel** [comment]
汗、CSDN的设定，0积分需要下载码了。
还不要1积分。我又改成1积分了。
你留个联系方式我发给你也行。
